# Generated by Django 5.1.6 on 2025-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add a new book'), ('can_change_book', 'can edit an existing book'), ('can_delete_bok', 'can delete a book')]},
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=2021),
            preserve_default=False,
        ),
    ]
